/* Auto-generated by Zynk - DO NOT EDIT */
/* Generated: 2025-12-12T17:54:32.562741 */

import { initBridge, request, createChannel, BridgeRequestError } from "./_internal";
import type { BridgeChannel, BridgeError } from "./_internal";

export { initBridge, BridgeRequestError };
export type { BridgeChannel, BridgeError };

// ============ Interfaces ============

export interface AgentConfig {
    provider?: string;
    modelId?: string;
    toolIds?: string[];
    instructions?: string[];
    name?: string | undefined;
    description?: string | undefined;
}

export interface AllChatsData {
    chats: Record<string, ChatData>;
}

export interface AllModelSettingsResponse {
    models: ModelSettingsInfo[];
}

export interface AllProvidersResponse {
    providers: ProviderConfig[];
}

export interface AutoTitleSettings {
    enabled?: boolean;
    prompt?: string;
    modelMode?: string;
    provider?: string;
    modelId?: string;
}

export interface AvailableModelsResponse {
    models: ModelInfo[];
}

export interface AvailableToolsResponse {
    tools: ToolInfo[];
}

export interface CancelRunRequest {
    messageId: string;
}

export interface ChatAgentConfigResponse {
    toolIds: string[];
    provider: string;
    modelId: string;
}

export interface ChatData {
    id?: string | undefined;
    title: string;
    messages?: ChatMessage[];
    model?: string | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
}

export interface ChatId {
    id: string;
}

export interface ChatMessage {
    id: string;
    role: string;
    content: string | ContentBlock[];
    createdAt?: string | undefined;
    toolCalls?: ToolCall[] | undefined;
}

export interface ContentBlock {
    type: string;
    content?: string | undefined;
    id?: string | undefined;
    toolName?: string | undefined;
    toolArgs?: Record<string, unknown> | undefined;
    toolResult?: string | undefined;
    isCompleted?: boolean | undefined;
    renderer?: string | undefined;
    requiresApproval?: boolean | undefined;
    approvalId?: string | undefined;
    approvalStatus?: string | undefined;
}

export interface ContinueMessageRequest {
    messageId: string;
    chatId: string;
    channel: unknown;
    modelId?: string | undefined;
}

export interface CreateChatInput {
    id?: string | undefined;
    title?: string | undefined;
    model?: string | undefined;
    agentConfig?: AgentConfig | undefined;
}

export interface DefaultToolsResponse {
    toolIds: string[];
}

export interface EditUserMessageRequest {
    messageId: string;
    newContent: string;
    chatId: string;
    channel: unknown;
    modelId?: string | undefined;
}

export interface GetMessageSiblingsRequest {
    messageId: string;
}

export interface Greeting {
    message: string;
}

export interface MessageSiblingInfo {
    id: string;
    sequence: number;
    isActive: boolean;
}

export interface ModelInfo {
    provider: string;
    modelId: string;
    displayName: string;
    isDefault?: boolean;
}

export interface ModelSettingsInfo {
    provider: string;
    modelId: string;
    parseThinkTags: boolean;
    reasoning: ReasoningInfo;
    thinkingTagPrompted?: ThinkingTagPromptInfo | undefined;
}

export interface Person {
    name: string;
}

export interface ProviderConfig {
    provider: string;
    apiKey?: string | undefined;
    baseUrl?: string | undefined;
    extra?: unknown | undefined;
    enabled?: boolean;
}

export interface ReasoningInfo {
    supports: boolean;
    isUserOverride: boolean;
}

export interface ReprocessMessageRequest {
    messageId: string;
}

export interface RespondToThinkingTagPromptInput {
    provider: string;
    modelId: string;
    accepted: boolean;
}

export interface RespondToToolApprovalInput {
    approvalId: string;
    approved: boolean;
    editedArgs?: Record<string, unknown> | undefined;
}

export interface RetryMessageRequest {
    messageId: string;
    chatId: string;
    channel: unknown;
    modelId?: string | undefined;
}

export interface SaveAutoTitleSettingsInput {
    enabled: boolean;
    prompt: string;
    modelMode: string;
    provider: string;
    modelId: string;
}

export interface SaveModelSettingsInput {
    provider: string;
    modelId: string;
    parseThinkTags?: boolean;
    reasoning?: ReasoningInfo | undefined;
}

export interface SaveProviderConfigInput {
    provider: string;
    apiKey?: string | undefined;
    baseUrl?: string | undefined;
    extra?: unknown | undefined;
    enabled?: boolean;
}

export interface SetDefaultToolsInput {
    toolIds: string[];
}

export interface StreamChatRequest {
    channel: unknown;
    messages: Record<string, unknown>[];
    modelId?: string | undefined;
    chatId?: string | undefined;
}

export interface SwitchToSiblingRequest {
    messageId: string;
    siblingId: string;
    chatId: string;
}

export interface ThinkingTagPromptInfo {
    prompted: boolean;
    declined: boolean;
}

export interface ToggleChatToolsInput {
    chatId: string;
    toolIds: string[];
}

export interface ToolCall {
    id: string;
    toolName: string;
    toolArgs: Record<string, unknown>;
    toolResult?: string | undefined;
    isCompleted?: boolean | undefined;
}

export interface ToolInfo {
    id: string;
    name?: string | undefined;
    description?: string | undefined;
    category?: string | undefined;
}

export interface UpdateChatInput {
    id: string;
    title?: string | undefined;
    model?: string | undefined;
}

export interface UpdateChatModelInput {
    chatId: string;
    provider: string;
    modelId: string;
}


// ============ Commands ============

/**
 * Cancel an active streaming run. Returns {cancelled: bool}
 */
export async function cancelRun(args: { body: CancelRunRequest }): Promise<unknown> {
    return request("cancel_run", { body: args.body });
}

/**
 * Continue incomplete assistant message from where it stopped.
 */
export async function continueMessage(args: { body: ContinueMessageRequest }): Promise<void> {
    return request("continue_message", { body: args.body });
}

export async function createChat(args: { body: CreateChatInput }): Promise<ChatData> {
    return request("create_chat", { body: args.body });
}

export async function deleteChat(args: { body: ChatId }): Promise<void> {
    return request("delete_chat", { body: args.body });
}

/**
 * Edit user message by creating sibling with new content.
 */
export async function editUserMessage(args: { body: EditUserMessageRequest }): Promise<void> {
    return request("edit_user_message", { body: args.body });
}

/**
 * Generate and update title for a chat based on its first message.
 * 
 * Args:
 * body: Contains chatId
 * 
 * Returns:
 * Dict with the new title or None if generation failed
 */
export async function generateChatTitle(args: { body: ChatId }): Promise<Record<string, unknown>> {
    return request("generate_chat_title", { body: args.body });
}

export async function getAllChats(): Promise<AllChatsData> {
    return request("get_all_chats", {});
}

/**
 * Get auto-title generation settings.
 * 
 * Returns:
 * Auto-title settings including enabled, prompt, and model configuration
 */
export async function getAutoTitleSettings(): Promise<AutoTitleSettings> {
    return request("get_auto_title_settings", {});
}

/**
 * Get list of available models based on configured providers.
 * 
 * Returns:
 * List of available models with provider, modelId, displayName, and isDefault
 */
export async function getAvailableModels(): Promise<AvailableModelsResponse> {
    return request("get_available_models", {});
}

/**
 * Get list of all available tools.
 * 
 * Returns:
 * List of tool information (id, name, description, category)
 */
export async function getAvailableTools(): Promise<AvailableToolsResponse> {
    return request("get_available_tools", {});
}

export async function getChat(args: { body: ChatId }): Promise<Record<string, unknown>> {
    return request("get_chat", { body: args.body });
}

/**
 * Get agent configuration for a chat (tools, provider, model).
 * 
 * Args:
 * body: Contains chatId
 * 
 * Returns:
 * Chat's agent configuration
 */
export async function getChatAgentConfig(args: { body: ChatId }): Promise<ChatAgentConfigResponse> {
    return request("get_chat_agent_config", { body: args.body });
}

/**
 * Get default tool IDs for new chats.
 * 
 * Returns:
 * List of default tool IDs
 */
export async function getDefaultTools(): Promise<DefaultToolsResponse> {
    return request("get_default_tools", {});
}

/**
 * Get all sibling messages for navigation UI.
 */
export async function getMessageSiblings(args: { body: GetMessageSiblingsRequest }): Promise<MessageSiblingInfo[]> {
    return request("get_message_siblings", { body: args.body });
}

/**
 * Get all model settings including reasoning capabilities.
 * 
 * Returns:
 * List of model settings with reasoning support flags
 */
export async function getModelSettings(): Promise<AllModelSettingsResponse> {
    return request("get_model_settings", {});
}

/**
 * Get all configured provider settings.
 * 
 * Returns:
 * List of provider configurations
 */
export async function getProviderSettings(): Promise<AllProvidersResponse> {
    return request("get_provider_settings", {});
}

export async function getVersion(): Promise<string> {
    return request("get_version", {});
}

export async function greet(args: { body: Person }): Promise<Greeting> {
    return request("greet", { body: args.body });
}

/**
 * Re-process a message to parse <think> tags from its content.
 * Returns {success: bool}
 */
export async function reprocessMessageThinkTags(args: { body: ReprocessMessageRequest }): Promise<unknown> {
    return request("reprocess_message_think_tags", { body: args.body });
}

/**
 * Handle user response to thinking tag detection prompt.
 * 
 * If accepted, enables parse_think_tags and reprocesses the current message.
 * If declined, stores thinkingTagPrompted: { prompted: true, declined: true } in extra.
 * 
 * Args:
 * body: User's response
 */
export async function respondToThinkingTagPrompt(args: { body: RespondToThinkingTagPromptInput }): Promise<void> {
    return request("respond_to_thinking_tag_prompt", { body: args.body });
}

/**
 * Respond to a tool approval request.
 * 
 * This unblocks the waiting pre-hook with the user's decision.
 * The approval status will be persisted when the tool completes.
 */
export async function respondToToolApproval(args: { body: RespondToToolApprovalInput }): Promise<unknown> {
    return request("respond_to_tool_approval", { body: args.body });
}

/**
 * Create sibling message and retry generation.
 */
export async function retryMessage(args: { body: RetryMessageRequest }): Promise<void> {
    return request("retry_message", { body: args.body });
}

/**
 * Save auto-title generation settings.
 * 
 * Args:
 * body: Auto-title settings to save
 */
export async function saveAutoTitleSettings(args: { body: SaveAutoTitleSettingsInput }): Promise<void> {
    return request("save_auto_title_settings", { body: args.body });
}

/**
 * Save or update model settings (including reasoning support).
 * 
 * Args:
 * body: Model settings to save
 */
export async function saveModelSettings(args: { body: SaveModelSettingsInput }): Promise<void> {
    return request("save_model_settings", { body: args.body });
}

/**
 * Save or update provider settings.
 * 
 * Args:
 * body: Provider configuration to save
 */
export async function saveProviderSettings(args: { body: SaveProviderConfigInput }): Promise<void> {
    return request("save_provider_settings", { body: args.body });
}

/**
 * Set default tool IDs for new chats.
 * 
 * Args:
 * body: Contains list of tool IDs to set as defaults
 */
export async function setDefaultTools(args: { body: SetDefaultToolsInput }): Promise<void> {
    return request("set_default_tools", { body: args.body });
}

export async function streamChat(args: { body: StreamChatRequest }): Promise<void> {
    return request("stream_chat", { body: args.body });
}

/**
 * Switch active branch to different sibling.
 */
export async function switchToSibling(args: { body: SwitchToSiblingRequest }): Promise<void> {
    return request("switch_to_sibling", { body: args.body });
}

/**
 * Update active tools for a chat session.
 * 
 * Args:
 * body: Contains chatId and list of tool IDs to activate
 */
export async function toggleChatTools(args: { body: ToggleChatToolsInput }): Promise<void> {
    return request("toggle_chat_tools", { body: args.body });
}

export async function updateChat(args: { body: UpdateChatInput }): Promise<ChatData> {
    return request("update_chat", { body: args.body });
}

/**
 * Switch the model/provider for a chat session.
 * 
 * Args:
 * body: Contains chatId, provider, and modelId
 */
export async function updateChatModel(args: { body: UpdateChatModelInput }): Promise<void> {
    return request("update_chat_model", { body: args.body });
}