/* eslint-disable */
/**
 * This file was automatically generated by pytauri-gen-ts.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source commands API,
 * and run pytauri-gen-ts to regenerate this file.
 */

import { pyInvoke } from "tauri-plugin-pytauri-api";
import type { InvokeOptions } from "@tauri-apps/api/core";

import type { Commands } from "./_apiTypes.d.ts";

export async function greet(
    body: Commands["greet"]["input"],
    options?: InvokeOptions
): Promise<Commands["greet"]["output"]> {
    return await pyInvoke("greet", body, options);
}

export async function getVersion(
    body: Commands["get_version"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_version"]["output"]> {
    return await pyInvoke("get_version", body, options);
}

/**
 * Get list of available models based on configured providers.
 *
 * Checks both environment variables and database provider settings.
 *
 * Returns:
 *     List of available models with provider, modelId, displayName, and isDefault
 */
export async function getAvailableModels(
    body: Commands["get_available_models"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_available_models"]["output"]> {
    return await pyInvoke("get_available_models", body, options);
}

/**
 * Get all configured provider settings.
 *
 * Returns:
 *     List of provider configurations
 */
export async function getProviderSettings(
    body: Commands["get_provider_settings"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_provider_settings"]["output"]> {
    return await pyInvoke("get_provider_settings", body, options);
}

/**
 * Save or update provider settings.
 *
 * Args:
 *     body: Provider configuration to save
 *     app_handle: Tauri app handle
 */
export async function saveProviderSettings(
    body: Commands["save_provider_settings"]["input"],
    options?: InvokeOptions
): Promise<Commands["save_provider_settings"]["output"]> {
    return await pyInvoke("save_provider_settings", body, options);
}

export async function getAllChats(
    body: Commands["get_all_chats"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_all_chats"]["output"]> {
    return await pyInvoke("get_all_chats", body, options);
}

export async function createChat(
    body: Commands["create_chat"]["input"],
    options?: InvokeOptions
): Promise<Commands["create_chat"]["output"]> {
    return await pyInvoke("create_chat", body, options);
}

export async function updateChat(
    body: Commands["update_chat"]["input"],
    options?: InvokeOptions
): Promise<Commands["update_chat"]["output"]> {
    return await pyInvoke("update_chat", body, options);
}

export async function deleteChat(
    body: Commands["delete_chat"]["input"],
    options?: InvokeOptions
): Promise<Commands["delete_chat"]["output"]> {
    return await pyInvoke("delete_chat", body, options);
}

export async function getChat(
    body: Commands["get_chat"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_chat"]["output"]> {
    return await pyInvoke("get_chat", body, options);
}

/**
 * Update active tools for a chat session.
 *
 * Args:
 *     body: Contains chatId and list of tool IDs to activate
 *     app_handle: Tauri app handle
 */
export async function toggleChatTools(
    body: Commands["toggle_chat_tools"]["input"],
    options?: InvokeOptions
): Promise<Commands["toggle_chat_tools"]["output"]> {
    return await pyInvoke("toggle_chat_tools", body, options);
}

/**
 * Switch the model/provider for a chat session.
 *
 * Args:
 *     body: Contains chatId, provider, and modelId
 *     app_handle: Tauri app handle
 */
export async function updateChatModel(
    body: Commands["update_chat_model"]["input"],
    options?: InvokeOptions
): Promise<Commands["update_chat_model"]["output"]> {
    return await pyInvoke("update_chat_model", body, options);
}

/**
 * Get list of all available tools.
 *
 * Returns:
 *     List of tool information (id, name, description, category)
 */
export async function getAvailableTools(
    body: Commands["get_available_tools"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_available_tools"]["output"]> {
    return await pyInvoke("get_available_tools", body, options);
}

/**
 * Stream chat completions via a Channel to the frontend.
 *
 * Saves messages incrementally to DB:
 * - User message saved immediately
 * - Assistant message created and updated as content streams
 */
export async function streamChat(
    body: Commands["stream_chat"]["input"],
    options?: InvokeOptions
): Promise<Commands["stream_chat"]["output"]> {
    return await pyInvoke("stream_chat", body, options);
}
