export interface ProviderImageAsset {
  src: string;
  alt: string;
  className: string;
}

export const PROVIDER_ICON_ASSETS = {
  AIHubMix: { src: '/providers/aihubmix.png', alt: 'AIHubMix', className: 'size-5 min-w-5 min-h-5' },
  Abacus: { src: '/providers/abacus.png', alt: 'Abacus', className: 'size-5 min-w-5 min-h-5' },
  Alibaba: { src: '/providers/alibaba.png', alt: 'Alibaba', className: 'size-5 min-w-5 min-h-5' },
  AwsBedrock: { src: '/providers/aws-bedrock.webp', alt: 'Amazon Bedrock', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  Azure: { src: '/providers/azure.png', alt: 'Azure', className: 'size-5 min-w-5 min-h-5' },
  AzureCognitiveServices: { src: '/providers/azure-cognitive-services.jpg', alt: 'Azure Cognitive Services', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  Baseten: { src: '/providers/baseten_logo.jpeg', alt: 'Baseten', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  Berget: { src: '/providers/bergetai_logo.jpeg', alt: 'Berget AI', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  Cerebras: { src: '/providers/cerebras.png', alt: 'Cerebras', className: 'size-5 min-w-5 min-h-5' },
  Chutes: { src: '/providers/chutes.png', alt: 'Chutes', className: 'size-5 min-w-5 min-h-5' },
  Claude: { src: '/providers/claude.png', alt: 'Claude', className: 'size-5 min-w-5 min-h-5 scale-105' },
  CloudFerro: { src: '/providers/cloudferro.png', alt: 'CloudFerro', className: 'size-5 min-w-5 min-h-5' },
  Cloudflare: { src: '/providers/Cloudflare_Logo.png', alt: 'Cloudflare', className: 'size-5 min-w-5 min-h-5' },
  Cohere: { src: '/providers/cohere-color.png', alt: 'Cohere', className: 'size-5 min-w-5 min-h-5' },
  Cortecs: { src: '/providers/cortecs.webp', alt: 'Cortecs', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  DeepInfra: { src: '/providers/deepinfra.png', alt: 'Deep Infra', className: 'size-5 min-w-5 min-h-5' },
  DeepSeek: { src: '/providers/deepseek-logo-icon.webp', alt: 'DeepSeek', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  Evroc: { src: '/providers/evroc_logo.jpeg', alt: 'evroc', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  FastRouter: { src: '/providers/fastrouter-logo.svg', alt: 'FastRouter', className: 'size-5 min-w-5 min-h-5 dark:invert' },
  FireworksAI: { src: '/providers/fireworks-ai-icon.webp', alt: 'Fireworks AI', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  Firmware: { src: '/providers/firmware.png', alt: 'Firmware', className: 'size-5 min-w-5 min-h-5' },
  Friendli: { src: '/providers/friendli.png', alt: 'Friendli', className: 'size-5 min-w-5 min-h-5' },
  Gemini: { src: '/providers/aistudio.png', alt: 'Google AI Studio', className: 'size-5 min-w-5 min-h-5' },
  GeminiCli: { src: '/providers/gemini.png', alt: 'Gemini CLI', className: 'size-5 min-w-5 min-h-5' },
  GitHubCopilot: { src: '/providers/brand-github-copilot.svg', alt: 'GitHub Copilot', className: 'size-5 min-w-5 min-h-5' },
  GitLab: { src: '/providers/gitlab.png', alt: 'GitLab', className: 'size-5 min-w-5 min-h-5' },
  Groq: { src: '/providers/groq.png', alt: 'Groq', className: 'size-5 min-w-5 min-h-5 rounded-md scale-105' },
  Helicone: { src: '/providers/helicone.png', alt: 'Helicone', className: 'size-5 min-w-5 min-h-5' },
  HuggingFace: { src: '/providers/huggingface.png', alt: 'Hugging Face', className: 'size-5 min-w-5 min-h-5' },
  IFlowCN: { src: '/providers/iflowcn.svg', alt: 'iFlow', className: 'size-5 min-w-5 min-h-5 dark:invert' },
  IONet: { src: '/providers/ionet.svg', alt: 'IO.NET', className: 'size-5 min-w-5 min-h-5 dark:invert' },
  Inception: { src: '/providers/inception.jpeg', alt: 'Inception', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  JieKou: { src: '/providers/jiekou-logo.svg', alt: 'Jiekou', className: 'size-5 min-w-5 min-h-5 dark:invert' },
  Kilo: { src: '/providers/kilo.png', alt: 'Kilo', className: 'size-5 min-w-5 min-h-5' },
  Kimi: { src: '/providers/kimi.png', alt: 'Kimi', className: 'size-5 min-w-5 min-h-5' },
  LMStudio: { src: '/providers/lmstudio.jpeg', alt: 'LM Studio', className: 'size-5 min-w-5 min-h-5 rounded-md scale-105' },
  Llama: { src: '/providers/meta_and_llama_logo.webp', alt: 'Llama', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  LucidQuery: { src: '/providers/lucidquery.jpeg', alt: 'LucidQuery', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  Meganova: { src: '/providers/meganova.svg', alt: 'Meganova', className: 'size-5 min-w-5 min-h-5 dark:invert' },
  MiniMax: { src: '/providers/minimax.png', alt: 'MiniMax', className: 'size-5 min-w-5 min-h-5' },
  Mistral: { src: '/providers/mistral.webp', alt: 'Mistral', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  Moark: { src: '/providers/moark.svg', alt: 'Moark', className: 'size-5 min-w-5 min-h-5 dark:invert' },
  ModelScope: { src: '/providers/modelscope.png', alt: 'ModelScope', className: 'size-5 min-w-5 min-h-5' },
  Moonshot: { src: '/providers/moonshot.png', alt: 'Moonshot AI', className: 'size-5 min-w-5 min-h-5' },
  Morph: { src: '/providers/morph.jpeg', alt: 'Morph', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  NanoGPT: { src: '/providers/nanogpt.webp', alt: 'NanoGPT', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  Nebius: { src: '/providers/nebius.jpeg', alt: 'Nebius', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  Nova: { src: '/providers/nova.webp', alt: 'Nova', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  Novita: { src: '/providers/novita.png', alt: 'NovitaAI', className: 'size-5 min-w-5 min-h-5' },
  Ollama: { src: '/providers/ollama.png', alt: 'Ollama', className: 'size-5 min-w-5 min-h-5 rounded-md scale-105' },
  OpenAI: { src: '/providers/openai.png', alt: 'OpenAI', className: 'size-5 min-w-5 min-h-5 dark:invert' },
  OpenRouter: { src: '/providers/openrouter.png', alt: 'OpenRouter', className: 'size-5 min-w-5 min-h-5' },
  Opencode: { src: '/providers/opencode.png', alt: 'OpenCode', className: 'size-5 min-w-5 min-h-5' },
  OvhCloud: { src: '/providers/ovhcloud.webp', alt: 'OVHcloud', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  P302AI: { src: '/providers/p302ai.png', alt: '302.AI', className: 'size-5 min-w-5 min-h-5' },
  Perplexity: { src: '/providers/perplexity.jpeg', alt: 'Perplexity', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  Poe: { src: '/providers/poe.jpeg', alt: 'Poe', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  PrivateModeAI: { src: '/providers/privatemode_ai.png', alt: 'PrivateMode AI', className: 'size-5 min-w-5 min-h-5' },
  Requesty: { src: '/providers/requesty.ico', alt: 'Requesty', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  Scaleway: { src: '/providers/scaleway.png', alt: 'Scaleway', className: 'size-5 min-w-5 min-h-5' },
  SiliconFlow: { src: '/providers/siliconflow.png', alt: 'SiliconFlow', className: 'size-5 min-w-5 min-h-5' },
  Stackit: { src: '/providers/stackit.jpeg', alt: 'STACKIT', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  StepFun: { src: '/providers/stepfun.jpg', alt: 'StepFun', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  Submodel: { src: '/providers/submodel.png', alt: 'Submodel', className: 'size-5 min-w-5 min-h-5' },
  Synthetic: { src: '/providers/synthetic.png', alt: 'Synthetic', className: 'size-5 min-w-5 min-h-5' },
  TogetherAI: { src: '/providers/together-ai.png', alt: 'Together AI', className: 'size-5 min-w-5 min-h-5' },
  UpstageAI: { src: '/providers/upstageai.jpeg', alt: 'Upstage', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  V0: { src: '/providers/v0.webp', alt: 'v0', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  VLLM: { src: '/providers/vllm.png', alt: 'vLLM', className: 'size-5 min-w-5 min-h-5' },
  Venice: { src: '/providers/venice.png', alt: 'Venice AI', className: 'size-5 min-w-5 min-h-5' },
  Vercel: { src: '/providers/vercel.svg', alt: 'Vercel', className: 'size-5 min-w-5 min-h-5 dark:invert' },
  VertexAI: { src: '/providers/vertex-ai-icon.webp', alt: 'Vertex AI', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  Vivgrid: { src: '/providers/vivgrid.png', alt: 'Vivgrid', className: 'size-5 min-w-5 min-h-5' },
  Vultr: { src: '/providers/vultr.png', alt: 'Vultr', className: 'size-5 min-w-5 min-h-5' },
  WandB: { src: '/providers/wandb.png', alt: 'Weights & Biases', className: 'size-5 min-w-5 min-h-5' },
  XAI: { src: '/providers/xai.jpg', alt: 'xAI', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
  Xiaomi: { src: '/providers/xiaomi.png', alt: 'Xiaomi', className: 'size-5 min-w-5 min-h-5' },
  ZAI: { src: '/providers/zai.png', alt: 'Z.AI', className: 'size-5 min-w-5 min-h-5' },
  ZhipuAI: { src: '/providers/zhipuai.jpg', alt: 'Zhipu AI', className: 'size-5 min-w-5 min-h-5 rounded-sm' },
} as const satisfies Record<string, ProviderImageAsset>;
