/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export type Name = string
export type Message = string
export type RootModelStr = string

/**
 * Commands Input and Output Schemas
 */
export interface Commands {
greet: {
input: Person
output: Greeting
}
get_version: {
input: void | undefined
output: RootModelStr
}
}
export interface Person {
name: Name
}
export interface Greeting {
message: Message
}
