/* eslint-disable */
/**
 * This file was automatically generated by pytauri-gen-ts.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source commands API,
 * and run pytauri-gen-ts to regenerate this file.
 */

import { pyInvoke } from "tauri-plugin-pytauri-api";
import type { InvokeOptions } from "@tauri-apps/api/core";

import type { Commands } from "./_apiTypes.d.ts";

export async function greet(
    body: Commands["greet"]["input"],
    options?: InvokeOptions
): Promise<Commands["greet"]["output"]> {
    return await pyInvoke("greet", body, options);
}

export async function getVersion(
    body: Commands["get_version"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_version"]["output"]> {
    return await pyInvoke("get_version", body, options);
}
