"""Declarative provider manifest.

Each entry maps a provider id to an adapter and its configuration.
Adding a new OpenAI-compatible provider is a single line here.
"""

from __future__ import annotations

MANIFEST_PROVIDERS = [
    {"id": "abacus", "adapter": "openai_compatible", "base_url": "https://routellm.abacus.ai/v1"},
    {"id": "aihubmix", "adapter": "openai_compatible", "base_url": "https://aihubmix.com/v1"},
    {"id": "alibaba", "adapter": "openai_compatible", "base_url": "https://dashscope-intl.aliyuncs.com/compatible-mode/v1"},
    {"id": "alibaba_cn", "adapter": "openai_compatible", "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1"},
    {"id": "amazon_bedrock", "adapter": "openai_compatible"},
    {"id": "azure", "adapter": "openai_compatible"},
    {"id": "azure_cognitive_services", "adapter": "openai_compatible"},
    {"id": "bailing", "adapter": "openai_compatible", "base_url": "https://api.tbox.cn/api/llm/v1/chat/completions"},
    {"id": "baseten", "adapter": "openai_compatible", "base_url": "https://inference.baseten.co/v1"},
    {"id": "berget", "adapter": "openai_compatible", "base_url": "https://api.berget.ai/v1"},
    {"id": "cerebras", "adapter": "openai_compatible", "base_url": "https://api.cerebras.ai/v1"},
    {"id": "chutes", "adapter": "openai_compatible", "base_url": "https://llm.chutes.ai/v1"},
    {"id": "cloudferro_sherlock", "adapter": "openai_compatible", "base_url": "https://api-sherlock.cloudferro.com/openai/v1/"},
    {"id": "cloudflare_ai_gateway", "adapter": "openai_compatible"},
    {"id": "cloudflare_workers_ai", "adapter": "openai_compatible", "base_url": "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/ai/v1"},
    {"id": "cortecs", "adapter": "openai_compatible", "base_url": "https://api.cortecs.ai/v1"},
    {"id": "deepinfra", "adapter": "openai_compatible", "base_url": "https://api.deepinfra.com/v1/openai"},
    {"id": "deepseek", "adapter": "openai_compatible", "base_url": "https://api.deepseek.com"},
    {"id": "evroc", "adapter": "openai_compatible", "base_url": "https://models.think.evroc.com/v1"},
    {"id": "fastrouter", "adapter": "openai_compatible", "base_url": "https://go.fastrouter.ai/api/v1"},
    {"id": "fireworks_ai", "adapter": "openai_compatible", "base_url": "https://api.fireworks.ai/inference/v1/"},
    {"id": "firmware", "adapter": "openai_compatible", "base_url": "https://app.firmware.ai/api/v1"},
    {"id": "friendli", "adapter": "openai_compatible", "base_url": "https://api.friendli.ai/serverless/v1"},
    {"id": "github_copilot_api", "adapter": "openai_compatible", "base_url": "https://api.githubcopilot.com"},
    {"id": "github_models", "adapter": "openai_compatible", "base_url": "https://models.github.ai/inference"},
    {"id": "gitlab", "adapter": "openai_compatible"},
    {"id": "google_vertex_anthropic", "adapter": "anthropic_compatible", "base_url": "https://api.anthropic.com"},
    {"id": "helicone", "adapter": "openai_compatible", "base_url": "https://ai-gateway.helicone.ai/v1"},
    {"id": "huggingface", "adapter": "openai_compatible", "base_url": "https://router.huggingface.co/v1"},
    {"id": "iflowcn", "adapter": "openai_compatible", "base_url": "https://apis.iflow.cn/v1"},
    {"id": "inception", "adapter": "openai_compatible", "base_url": "https://api.inceptionlabs.ai/v1/"},
    {"id": "inference", "adapter": "openai_compatible", "base_url": "https://inference.net/v1"},
    {"id": "io_net", "adapter": "openai_compatible", "base_url": "https://api.intelligence.io.solutions/api/v1"},
    {"id": "jiekou", "adapter": "openai_compatible", "base_url": "https://api.jiekou.ai/openai"},
    {"id": "kilo", "adapter": "openai_compatible", "base_url": "https://api.kilo.ai/api/gateway"},
    {"id": "kimi_for_coding", "adapter": "anthropic_compatible", "base_url": "https://api.kimi.com/coding/v1"},
    {"id": "kuae_cloud_coding_plan", "adapter": "openai_compatible", "base_url": "https://coding-plan-endpoint.kuaecloud.net/v1"},
    {"id": "llama", "adapter": "openai_compatible", "base_url": "https://api.llama.com/compat/v1/"},
    {"id": "lucidquery", "adapter": "openai_compatible", "base_url": "https://lucidquery.com/api/v1"},
    {"id": "meganova", "adapter": "openai_compatible", "base_url": "https://api.meganova.ai/v1"},
    {"id": "minimax", "adapter": "anthropic_compatible", "base_url": "https://api.minimax.io/anthropic/v1"},
    {"id": "minimax_coding_plan", "adapter": "anthropic_compatible", "base_url": "https://api.minimax.io/anthropic/v1"},
    {"id": "minimax_cn", "adapter": "anthropic_compatible", "base_url": "https://api.minimaxi.com/anthropic/v1"},
    {"id": "minimax_cn_coding_plan", "adapter": "anthropic_compatible", "base_url": "https://api.minimaxi.com/anthropic/v1"},
    {"id": "mistral", "adapter": "openai_compatible", "base_url": "https://api.mistral.ai/v1"},
    {"id": "moark", "adapter": "openai_compatible", "base_url": "https://moark.com/v1"},
    {"id": "modelscope", "adapter": "openai_compatible", "base_url": "https://api-inference.modelscope.cn/v1"},
    {"id": "moonshotai", "adapter": "openai_compatible", "base_url": "https://api.moonshot.ai/v1"},
    {"id": "moonshotai_cn", "adapter": "openai_compatible", "base_url": "https://api.moonshot.cn/v1"},
    {"id": "morph", "adapter": "openai_compatible", "base_url": "https://api.morphllm.com/v1"},
    {"id": "nano_gpt", "adapter": "openai_compatible", "base_url": "https://nano-gpt.com/api/v1"},
    {"id": "nebius", "adapter": "openai_compatible", "base_url": "https://api.tokenfactory.nebius.com/v1"},
    {"id": "nova", "adapter": "openai_compatible", "base_url": "https://api.nova.amazon.com/v1"},
    {"id": "novita_ai", "adapter": "openai_compatible", "base_url": "https://api.novita.ai/openai"},
    {"id": "nvidia", "adapter": "openai_compatible", "base_url": "https://integrate.api.nvidia.com/v1"},
    {"id": "ollama_cloud", "adapter": "openai_compatible", "base_url": "https://ollama.com/v1"},
    {"id": "opencode", "adapter": "openai_compatible", "base_url": "https://opencode.ai/zen/v1"},
    {"id": "ovhcloud", "adapter": "openai_compatible", "base_url": "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1"},
    {"id": "p302ai", "adapter": "openai_compatible", "base_url": "https://api.302.ai/v1", "aliases": ["302ai"]},
    {"id": "perplexity", "adapter": "openai_compatible", "base_url": "https://api.perplexity.ai"},
    {"id": "poe", "adapter": "openai_compatible", "base_url": "https://api.poe.com/v1"},
    {"id": "privatemode_ai", "adapter": "openai_compatible", "base_url": "http://localhost:8080/v1"},
    {"id": "qihang_ai", "adapter": "openai_compatible", "base_url": "https://api.qhaigc.net/v1"},
    {"id": "qiniu_ai", "adapter": "openai_compatible", "base_url": "https://api.qnaigc.com.com/v1"},
    {"id": "requesty", "adapter": "openai_compatible", "base_url": "https://router.requesty.ai/v1"},
    {"id": "sap_ai_core", "adapter": "openai_compatible"},
    {"id": "scaleway", "adapter": "openai_compatible", "base_url": "https://api.scaleway.ai/v1"},
    {"id": "siliconflow", "adapter": "openai_compatible", "base_url": "https://api.siliconflow.com/v1"},
    {"id": "siliconflow_cn", "adapter": "openai_compatible", "base_url": "https://api.siliconflow.cn/v1"},
    {"id": "stackit", "adapter": "openai_compatible", "base_url": "https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1"},
    {"id": "stepfun", "adapter": "openai_compatible", "base_url": "https://api.stepfun.com/v1"},
    {"id": "submodel", "adapter": "openai_compatible", "base_url": "https://llm.submodel.ai/v1"},
    {"id": "synthetic", "adapter": "openai_compatible", "base_url": "https://api.synthetic.new/v1"},
    {"id": "togetherai", "adapter": "openai_compatible", "base_url": "https://api.together.xyz/v1"},
    {"id": "upstage", "adapter": "openai_compatible", "base_url": "https://api.upstage.ai/v1/solar"},
    {"id": "v0", "adapter": "openai_compatible", "base_url": "https://api.v0.dev/v1"},
    {"id": "venice", "adapter": "openai_compatible", "base_url": "https://api.venice.ai/api/v1"},
    {"id": "vercel", "adapter": "openai_compatible", "base_url": "https://gateway.ai.vercel.com/v1"},
    {"id": "vivgrid", "adapter": "openai_compatible", "base_url": "https://api.vivgrid.com/v1"},
    {"id": "vultr", "adapter": "openai_compatible", "base_url": "https://api.vultrinference.com/v1"},
    {"id": "wandb", "adapter": "openai_compatible", "base_url": "https://api.inference.wandb.ai/v1"},
    {"id": "xai", "adapter": "openai_compatible", "base_url": "https://api.x.ai/v1"},
    {"id": "xiaomi", "adapter": "openai_compatible", "base_url": "https://api.xiaomimimo.com/v1"},
    {"id": "zai", "adapter": "openai_compatible", "base_url": "https://api.z.ai/api/paas/v4"},
    {"id": "zai_coding_plan", "adapter": "openai_compatible", "base_url": "https://api.z.ai/api/coding/paas/v4"},
    {"id": "zenmux", "adapter": "anthropic_compatible", "base_url": "https://zenmux.ai/api/anthropic/v1"},
    {"id": "zhipuai", "adapter": "openai_compatible", "base_url": "https://open.bigmodel.cn/api/paas/v4"},
    {"id": "zhipuai_coding_plan", "adapter": "openai_compatible", "base_url": "https://open.bigmodel.cn/api/coding/paas/v4"},
]
